import "./globals.sass";
import "./globals-variable-style.sass";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./_components/_common/Header/page";
import Footer from "./_components/_common/Footer/page";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <Header />
                {children}

                <Footer />
            </body>
        </html>
    );
}
//  Root layouts must contain html and body tags.
